<?php

class MimeMapMinimal {

	const MIME_EXTENSIONS = [
		'application/ogg' => 'ogx ogg ogm ogv oga spx opus',
		'application/pdf' => 'pdf',
		'application/vnd.oasis.opendocument.chart' => 'odc',
		'application/vnd.oasis.opendocument.chart-template' => 'otc',
		'application/vnd.oasis.opendocument.database' => 'odb',
		'application/vnd.oasis.opendocument.formula' => 'odf',
		'application/vnd.oasis.opendocument.formula-template' => 'otf',
		'application/vnd.oasis.opendocument.graphics' => 'odg',
		'application/vnd.oasis.opendocument.graphics-template' => 'otg',
		'application/vnd.oasis.opendocument.image' => 'odi',
		'application/vnd.oasis.opendocument.image-template' => 'oti',
		'application/vnd.oasis.opendocument.presentation' => 'odp',
		'application/vnd.oasis.opendocument.presentation-template' => 'otp',
		'application/vnd.oasis.opendocument.spreadsheet' => 'ods',
		'application/vnd.oasis.opendocument.spreadsheet-template' => 'ots',
		'application/vnd.oasis.opendocument.text' => 'odt',
		'application/vnd.oasis.opendocument.text-master' => 'otm',
		'application/vnd.oasis.opendocument.text-template' => 'ott',
		'application/vnd.oasis.opendocument.text-web' => 'oth',
		'application/javascript' => 'js',
		'application/x-shockwave-flash' => 'swf',
		'audio/midi' => 'mid midi kar',
		'audio/mpeg' => 'mpga mpa mp2 mp3',
		'audio/x-aiff' => 'aif aiff aifc',
		'audio/x-wav' => 'wav',
		'audio/ogg' => 'oga spx ogg opus',
		'audio/opus' => 'opus ogg oga spx',
		'image/x-bmp' => 'bmp',
		'image/gif' => 'gif',
		'image/jpeg' => 'jpeg jpg jpe',
		'image/png' => 'png',
		'image/svg+xml' => 'svg',
		'image/svg' => 'svg',
		'image/tiff' => 'tiff tif',
		'image/vnd.djvu' => 'djvu',
		'image/x.djvu' => 'djvu',
		'image/x-djvu' => 'djvu',
		'image/x-portable-pixmap' => 'ppm',
		'image/x-xcf' => 'xcf',
		'text/plain' => 'txt',
		'text/html' => 'html htm',
		'video/ogg' => 'ogv ogm ogg',
		'video/mpeg' => 'mpg mpeg',
	];

	const MEDIA_TYPES = [
		'OFFICE' => [
			'application/pdf',
			'application/vnd.oasis.opendocument.chart',
			'application/vnd.oasis.opendocument.chart-template',
			'application/vnd.oasis.opendocument.database',
			'application/vnd.oasis.opendocument.formula',
			'application/vnd.oasis.opendocument.formula-template',
			'application/vnd.oasis.opendocument.graphics',
			'application/vnd.oasis.opendocument.graphics-template',
			'application/vnd.oasis.opendocument.image',
			'application/vnd.oasis.opendocument.image-template',
			'application/vnd.oasis.opendocument.presentation',
			'application/vnd.oasis.opendocument.presentation-template',
			'application/vnd.oasis.opendocument.spreadsheet',
			'application/vnd.oasis.opendocument.spreadsheet-template',
			'application/vnd.oasis.opendocument.text',
			'application/vnd.oasis.opendocument.text-template',
			'application/vnd.oasis.opendocument.text-master',
			'application/vnd.oasis.opendocument.text-web',
		],
		'EXECUTABLE' => [
			'application/javascript',
			'text/javascript',
			'application/x-javascript',
		],
		'MULTIMEDIA' => [
			'application/x-shockwave-flash',
			'application/ogg',
			'audio/ogg',
			'video/ogg',
		],
		'AUDIO' => [
			'audio/midi',
			'audio/x-aiff',
			'audio/x-wav',
			'audio/mp3',
			'audio/mpeg',
		],
		'BITMAP' => [
			'image/x-bmp',
			'image/x-ms-bmp',
			'image/bmp',
			'image/gif',
			'image/jpeg',
			'image/png',
			'image/tiff',
			'image/vnd.djvu',
			'image/x-xcf',
			'image/x-portable-pixmap',
		],
		'DRAWING' => [
			'image/svg+xml',
		],
		'TEXT' => [
			'text/plain',
			'text/html',
		],
		'VIDEO' => [
			'video/ogg',
			'video/mpeg',
		],
		'UNKNOWN' => [
			'unknown/unknown',
			'application/octet-stream',
			'application/x-empty',
		],
	];

	const MIME_TYPE_ALIASES = [
		'text/javascript' => 'application/javascript',
		'application/x-javascript' => 'application/javascript',
		'audio/mpeg' => 'audio/mp3',
		'audio/ogg' => 'application/ogg',
		'video/ogg' => 'application/ogg',
		'image/x-ms-bmp' => 'image/x-bmp',
		'image/bmp' => 'image/x-bmp',
		'application/octet-stream' => 'unknown/unknown',
		'application/x-empty' => 'unknown/unknown',
	];
};
